(()=>{'use strict';const courses=window.COURSES,groups=window.GROUPS,colors={math:'#3266ce',model:'#008c80',ai:'#7853c1',code:'#c27522',general:'#687589',practice:'#a64c73'};const gantt=document.querySelector('#gantt'),filters=document.querySelector('#filters'),search=document.querySelector('#search'),dialog=document.querySelector('#course-dialog');let category='all',semester=1,view=window.matchMedia('(max-width:700px)').matches?'semester':'gantt';const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));filters.innerHTML=Object.entries({all:'Все дисциплины',...groups}).map(([id,name])=>`<button data-filter="${id}" aria-pressed="${id==='all'}" style="--category:${colors[id]||'#102c4d'}">${name}</button>`).join('');
function renderGantt(){const q=search.value.trim().toLocaleLowerCase('ru');const visible=courses.filter(c=>(category==='all'||c.group===category)&&c.name.toLocaleLowerCase('ru').includes(q));let html='<div class="gantt-header"><div>Дисциплина / семестр</div>'+Array.from({length:10},(_,i)=>`<div>${i+1}<small>${Math.floor(i/2)+1} курс</small></div>`).join('')+'</div>';for(const [key,label]of Object.entries(groups)){const items=visible.filter(c=>c.group===key).sort((a,b)=>a.semesters[0]-b.semesters[0]||a.id.localeCompare(b.id));if(!items.length)continue;html+=`<div class="group-label" style="--category:${colors[key]}">${label} · ${items.length}</div>`;for(const c of items){const optional=c.kind.includes('выбору')||c.kind==='Факультатив';const runs=[];for(const s of c.semesters){const last=runs.at(-1);if(last&&last.at(-1)===s-1)last.push(s);else runs.push([s]);}html+=`<div class="course-row" style="--category:${colors[key]}"><button class="course-name" data-course="${esc(c.id)}">${esc(c.name)}${optional?`<small>${esc(c.kind)}</small>`:''}</button>`+Array.from({length:10},(_,i)=>`<div class="cell" style="grid-column:${i+2}"></div>`).join('');for(const run of runs)html+=`<button class="bar ${optional?'optional':''}" style="grid-column:${run[0]+1}/span ${run.length}" data-course="${esc(c.id)}" aria-label="${esc(c.name)}, семестры ${run.join(', ')}. Открыть описание">${run.length>1?run[0]+'–'+run.at(-1):run[0]}</button>`;html+='</div>';}}if(!visible.length)html+='<p class="empty">Ничего не найдено. Попробуйте другое название или раздел.</p>';gantt.innerHTML=html;document.querySelector('#count').textContent=`Показано: ${visible.length} из ${courses.length} дисциплин, практик и итоговых работ`;}
function renderSemester(){
 const q=search.value.trim().toLocaleLowerCase('ru');
 const selected=courses.filter(c=>c.semesters.includes(semester)&&(category==='all'||c.group===category)&&c.name.toLocaleLowerCase('ru').includes(q));
 document.querySelector('.semester-picker').innerHTML=Array.from({length:10},(_,i)=>`<button data-semester="${i+1}" aria-pressed="${semester===i+1}"><span>${i+1}</span><small>семестр</small></button>`).join('');
 document.querySelector('#semester-list').innerHTML=`<div class="semester-title"><h3>${semester} семестр</h3><span>${Math.ceil(semester/2)} курс · ${selected.length} дисциплин и практик</span></div>`+selected.map(c=>`<button class="semester-course" data-course="${esc(c.id)}" style="--category:${colors[c.group]}"><span class="semester-course-title">${esc(c.name)}</span><span class="semester-course-meta">${esc(groups[c.group])}${c.kind.includes('выбору')||c.kind==='Факультатив'?' · '+esc(c.kind):''}</span></button>`).join('')+(selected.length?'':'<p class="empty">В этом семестре ничего не найдено. Выберите другой семестр или измените фильтр.</p>');
 if(view==='semester')document.querySelector('#count').textContent=`${semester} семестр: ${selected.length} дисциплин и практик`;
}
function render(){renderGantt();renderSemester();document.querySelector('.gantt-scroll').hidden=view!=='gantt';document.querySelector('#semester-panel').hidden=view!=='semester';document.querySelector('.scroll-hint').hidden=view!=='gantt';document.querySelector('.chart-meta>span:last-child').hidden=view!=='gantt';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));}
document.querySelector('.plan-view').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;view=b.dataset.view;render();});
document.querySelector('.semester-picker').addEventListener('click',e=>{const b=e.target.closest('[data-semester]');if(!b)return;semester=Number(b.dataset.semester);render();});
function careerText(c){
 if(c.name.includes('преподавания')||c.name==='Педагогика и психология')return 'Преподавателю математики — чтобы объяснять сложные темы, создавать задания и понимать, как учатся люди.';
 if(c.group==='general')return '';
 return {math:'Специалисту по моделированию, исследователю и разработчику ИИ — как математическая основа для постановки и решения задач.',model:'Специалисту по математическому моделированию и исследователю — для описания процессов, вычислительных экспериментов и проверки результатов.',ai:'Специалисту по машинному обучению и аналитику данных — для построения моделей, проверки прогнозов и исследования закономерностей.',code:'Разработчику научного программного обеспечения и систем ИИ — для создания надёжных вычислительных инструментов.',practice:'Исследователю и разработчику — чтобы пройти путь от постановки задачи до проверенного результата.'}[c.group]||'';
}
function openCourse(id){const c=courses.find(c=>c.id===id);if(!c)return;document.querySelector('#detail').innerHTML=`<div style="--category:${colors[c.group]}"><div class="detail-tag">${esc(groups[c.group])} · ${esc(c.kind)}</div><h2 class="detail-title" id="detail-title">${esc(c.name)}</h2><div class="detail-meta"><span>Семестры: ${c.semesters.join(', ')}</span><span>${c.credits} з.е.</span><span>${c.hours} часов</span></div><div class="detail-block"><h3>Что изучаем</h3><p>${esc(c.about)}</p></div><div class="detail-block why"><h3>Зачем это нужно?</h3><p>${esc(c.why)}</p></div><div class="detail-block"><h3>Например, вы сможете</h3><p>${esc(c.example)}</p></div>${careerText(c)?`<div class="detail-block"><h3>Кому пригодится в работе</h3><p>${esc(careerText(c))}</p></div>`:''}${c.kind.includes('выбору')?'<div class="detail-block"><p>В этой паре выбирается один из двух курсов.</p></div>':''}</div>`;dialog.showModal();dialog.scrollTop=0;}
filters.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;category=b.dataset.filter;filters.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render();});search.addEventListener('input',render);document.addEventListener('click',e=>{const b=e.target.closest('[data-course]');if(b)openCourse(b.dataset.course);});dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});render();
const canvas=document.querySelector('#surface'),ctx=canvas.getContext('2d'),slider=document.querySelector('#damping');function draw(){const r=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=r.width*dpr;canvas.height=r.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);const alpha=Number(slider.value)/100;document.querySelector('#alpha').textContent='α = '+alpha.toFixed(2);const scale=r.width/22;const project=(x,y,z)=>[r.width/2+(x-y)*scale*.66,r.height*.51+(x+y)*scale*.23-z*scale*1.95];ctx.lineWidth=.7;for(let axis=0;axis<2;axis++)for(let i=-24;i<=24;i++){ctx.beginPath();for(let j=-24;j<=24;j++){const x=(axis?j:i)/4,y=(axis?i:j)/4,rad=Math.hypot(x,y),z=Math.sin(rad*1.65)*Math.exp(-alpha*rad),p=project(x,y,z);j===-24?ctx.moveTo(...p):ctx.lineTo(...p);}ctx.strokeStyle=axis?'rgba(71,217,207,.58)':'rgba(81,151,236,.45)';ctx.stroke();}}slider.addEventListener('input',draw);new ResizeObserver(draw).observe(canvas);draw();})();
